title: Choyeon Hong
description: data-scientist
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "choyeon-hong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Choyeon Hong # add your name
author-img: cy.jpg # add your photo
about-author: I am currently staying at South Korea. Never Be Ordinary!! # add description
social-twitter: TwitterKorea # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: # add your Github handle
social-linkedin: choyeon-hong-920901 # add your Linkedin handle
social-email: eunice1615@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
